
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://SkIrfanAli:journalapp9749@cluster0.b7kqaod.mongodb.net/journalApp?retryWrites=true&w=majority
spring.data.mongodb.database=journalApp
spring.data.mongodb.auto-index-creation=true

#if authentication if available so we have to add the username and password too
#spring.data.mongodb.username=root
#spring.data.mongodb.password=root

#logging.level.root=ERROR
#logging.level.org.mongodb.driver=ERROR


# Kafka Bootstrap Server
spring.kafka.bootstrap-servers=pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092

# Security
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN

# Authentication
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='4OFQG65GISTOCKYH' password='cfltgZ5oVDFzvUmdUNOo3w9UcBHUOjLgn3JN0aGv08dyvO84LgPp5t9I3hV198GA';

# Timeout
spring.kafka.properties.session.timeout.ms=45000

# Client ID
spring.kafka.client-id=ccloud-springboot-client-a58dd432-ccab-44ed-92d1-1d7b1ef1104b

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=weekly-sentiment-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trusted Package
spring.kafka.consumer.properties.spring.json.trusted.packages=net.edigest.journalApp.model